set shell := ["pwsh", "-Command"]

venv_dir := ".venv"
venv_python := venv_dir + "/Scripts/python.exe"

default:
    @just --list

clean:
    Write-Host -Message "nothing to clean"

clean-setup:
    @just clean
    if (Test-Path -Path "{{venv_dir}}" -PathType Container) { Remove-Item -Path "{{venv_dir}}" -Recurse -Force }

setup:
    & "py" "setup.py"

build:
    @just setup
    & "{{venv_python}}" "src/generate_archipelago_files.py"
    & "{{venv_python}}" "src/generate_outward_files.py"

test:
    Write-Host -Message "nothing to test"
