using System.Collections.Generic;

namespace OutwardArchipelago.Archipelago
{
    internal class ArchipelagoItemManager
    {
        internal static ArchipelagoItemManager Instance { get; private set; } = new();

        private readonly IReadOnlyDictionary<long, IOutwardGiver> Givers = new Dictionary<long, IOutwardGiver>
        {
            { APWorldItem.AnglerShield, new ItemGiver(OutwardItem.AnglerShield) },
            { APWorldItem.AntiquePlateBoots, new ItemGiver(OutwardItem.AntiquePlateBoots) },
            { APWorldItem.AntiquePlateGarb, new ItemGiver(OutwardItem.AntiquePlateGarb) },
            { APWorldItem.AntiquePlateSallet, new ItemGiver(OutwardItem.AntiquePlateSallet) },
            { APWorldItem.BlueSandArmor, new ItemGiver(OutwardItem.BlueSandArmor) },
            { APWorldItem.BlueSandBoots, new ItemGiver(OutwardItem.BlueSandBoots) },
            { APWorldItem.BlueSandHelm, new ItemGiver(OutwardItem.BlueSandHelm) },
            { APWorldItem.Brand, new ItemGiver(OutwardItem.Brand) },
            { APWorldItem.BrassWolfBackpack, new ItemGiver(OutwardItem.BrassWolfBackpack) },
            { APWorldItem.CeremonialBow, new ItemGiver(OutwardItem.CeremonialBow) },
            { APWorldItem.CompasswoodStaff, new ItemGiver(OutwardItem.CompasswoodStaff) },
            { APWorldItem.CopalArmor, new ItemGiver(OutwardItem.CopalArmor) },
            { APWorldItem.CopalBoots, new ItemGiver(OutwardItem.CopalBoots) },
            { APWorldItem.CopalHelm, new ItemGiver(OutwardItem.CopalHelm) },
            { APWorldItem.CrackedRedMoon, new ItemGiver(OutwardItem.CrackedRedMoon) },
            { APWorldItem.DepoweredBludgeon, new ItemGiver(OutwardItem.DepoweredBludgeon) },
            { APWorldItem.DistortedExperiment, new ItemGiver(OutwardItem.DistortedExperiment) },
            { APWorldItem.DreamerHalberd, new ItemGiver(OutwardItem.DreamerHalberd) },
            { APWorldItem.Duty, new ItemGiver(OutwardItem.Duty) },
            { APWorldItem.ExperimentalChakram, new ItemGiver(OutwardItem.ExperimentalChakram) },
            { APWorldItem.FabulousPalladiumShield, new ItemGiver(OutwardItem.FabulousPalladiumShield) },
            { APWorldItem.FossilizedGreataxe, new ItemGiver(OutwardItem.FossilizedGreataxe) },
            { APWorldItem.GepsLongblade, new ItemGiver(OutwardItem.GepsLongblade) },
            { APWorldItem.GhostParallel, new ItemGiver(OutwardItem.GhostParallel) },
            { APWorldItem.GildedShiverOfTramontane, new ItemGiver(OutwardItem.GildedShiverOfTramontane) },
            { APWorldItem.GoldLichArmor, new ItemGiver(OutwardItem.GoldLichArmor) },
            { APWorldItem.GoldLichBoots, new ItemGiver(OutwardItem.GoldLichBoots) },
            { APWorldItem.GoldLichMask, new ItemGiver(OutwardItem.GoldLichMask) },
            { APWorldItem.GoldLichSpear, new ItemGiver(OutwardItem.GoldLichSpear) },
            { APWorldItem.Grind, new ItemGiver(OutwardItem.Grind) },
            { APWorldItem.JadeLichBoots, new ItemGiver(OutwardItem.JadeLichBoots) },
            { APWorldItem.JadeLichMask, new ItemGiver(OutwardItem.JadeLichMask) },
            { APWorldItem.JadeLichRobes, new ItemGiver(OutwardItem.JadeLichRobes) },
            { APWorldItem.JadeLichStaff, new ItemGiver(OutwardItem.JadeLichStaff) },
            { APWorldItem.KrypteiaTombKey, new ItemGiver(OutwardItem.KrypteiaTombKey) },
            { APWorldItem.LightMendersBackpack, new ItemGiver(OutwardItem.LightMendersBackpack) },
            { APWorldItem.LightMendersLexicon, new ItemGiver(OutwardItem.LightMendersLexicon) },
            { APWorldItem.MefinosTradeBackpack, new ItemGiver(OutwardItem.MefinosTradeBackpack) },
            { APWorldItem.MertonsFirepoker, new ItemGiver(OutwardItem.MertonsFirepoker) },
            { APWorldItem.MertonsRibcage, new ItemGiver(OutwardItem.MertonsRibcage) },
            { APWorldItem.MertonsShinbones, new ItemGiver(OutwardItem.MertonsShinbones) },
            { APWorldItem.MertonsSkull, new ItemGiver(OutwardItem.MertonsSkull) },
            { APWorldItem.Murmure, new ItemGiver(OutwardItem.Murmure) },
            { APWorldItem.MyrmitaurHavenGateKey, new ItemGiver(OutwardItem.MyrmitaurHavenGateKey) },
            { APWorldItem.MysteriousChakram, new ItemGiver(OutwardItem.MysteriousChakram) },
            { APWorldItem.MysteriousLongBlade, new ItemGiver(OutwardItem.MysteriousLongblade) },
            { APWorldItem.OrnateBoneShield, new ItemGiver(OutwardItem.OrnateBoneShield) },
            { APWorldItem.PalladiumArmor, new ItemGiver(OutwardItem.PalladiumArmor) },
            { APWorldItem.PalladiumBoots, new ItemGiver(OutwardItem.PalladiumBoots) },
            { APWorldItem.PalladiumHelm, new ItemGiver(OutwardItem.PalladiumHelm) },
            { APWorldItem.PearlescentMail, new ItemGiver(OutwardItem.PearlescentMail) },
            { APWorldItem.PetrifiedWoodArmor, new ItemGiver(OutwardItem.PetrifiedWoodArmor) },
            { APWorldItem.PetrifiedWoodBoots, new ItemGiver(OutwardItem.PetrifiedWoodBoots) },
            { APWorldItem.PetrifiedWoodHelm, new ItemGiver(OutwardItem.PetrifiedWoodHelm) },
            { APWorldItem.PillarGreathammer, new ItemGiver(OutwardItem.PillarGreathammer) },
            { APWorldItem.PorcelainFists, new ItemGiver(OutwardItem.PorcelainFists) },
            { APWorldItem.RedLadysDagger, new ItemGiver(OutwardItem.RedLadysDagger) },
            { APWorldItem.RevenantMoon, new ItemGiver(OutwardItem.RevenantMoon) },
            { APWorldItem.RotwoodStaff, new ItemGiver(OutwardItem.RotwoodStaff) },
            { APWorldItem.RuinedHalberd, new ItemGiver(OutwardItem.RuinedHalberd) },
            { APWorldItem.RustedSpear, new ItemGiver(OutwardItem.RustedSpear) },
            { APWorldItem.RustLichArmor, new ItemGiver(OutwardItem.RustLichArmor) },
            { APWorldItem.RustLichBoots, new ItemGiver(OutwardItem.RustLichBoots) },
            { APWorldItem.RustLichHelmet, new ItemGiver(OutwardItem.RustLichHelmet) },
            { APWorldItem.Sandrose, new ItemGiver(OutwardItem.Sandrose) },
            { APWorldItem.ScarletBoots, new ItemGiver(OutwardItem.ScarletBoots) },
            { APWorldItem.ScarletLichsIdol, new ItemGiver(OutwardItem.ScarletLichsIdol) },
            { APWorldItem.ScarletMask, new ItemGiver(OutwardItem.ScarletMask) },
            { APWorldItem.ScarletRobes, new ItemGiver(OutwardItem.ScarletRobes) },
            { APWorldItem.ScarredDagger, new ItemGiver(OutwardItem.ScarredDagger) },
            { APWorldItem.ScepterOfTheCruelPriest, new ItemGiver(OutwardItem.ScepterOfTheCruelPriest) },
            { APWorldItem.SealedMace, new ItemGiver(OutwardItem.SealedMace) },
            { APWorldItem.Shriek, new ItemGiver(OutwardItem.Shriek) },
            { APWorldItem.SkycrownMace, new ItemGiver(OutwardItem.SkycrownMace) },
            { APWorldItem.SlumberingShield, new ItemGiver(OutwardItem.SlumberingShield) },
            { APWorldItem.SmellySealedBox, new ItemGiver(OutwardItem.SmellySealedBox) },
            { APWorldItem.StarchildClaymore, new ItemGiver(OutwardItem.StarchildClaymore) },
            { APWorldItem.StrangeRustedSword, new ItemGiver(OutwardItem.StrangeRustedSword) },
            { APWorldItem.SunfallAxe, new ItemGiver(OutwardItem.SunfallAxe) },
            { APWorldItem.TenebrousArmor, new ItemGiver(OutwardItem.TenebrousArmor) },
            { APWorldItem.TenebrousBoots, new ItemGiver(OutwardItem.TenebrousBoots) },
            { APWorldItem.TenebrousHelm, new ItemGiver(OutwardItem.TenebrousHelm) },
            { APWorldItem.ThriceWroughtHalberd, new ItemGiver(OutwardItem.ThriceWroughtHalberd) },
            { APWorldItem.Tokebakicit, new ItemGiver(OutwardItem.Tokebakicit) },
            { APWorldItem.TsarArmor, new ItemGiver(OutwardItem.TsarArmor) },
            { APWorldItem.TsarBoots, new ItemGiver(OutwardItem.TsarBoots) },
            { APWorldItem.TsarFists, new ItemGiver(OutwardItem.TsarFists) },
            { APWorldItem.TsarHelm, new ItemGiver(OutwardItem.TsarHelm) },
            { APWorldItem.UnusualKnuckles, new ItemGiver(OutwardItem.UnusualKnuckles) },
            { APWorldItem.WarmAxe, new ItemGiver(OutwardItem.WarmAxe) },
            { APWorldItem.WerligSpear, new ItemGiver(OutwardItem.WerligSpear) },
            { APWorldItem.WillOWisp, new ItemGiver(OutwardItem.WillOWisp) },
            { APWorldItem.WorldedgeGreataxe, new ItemGiver(OutwardItem.WorldedgeGreataxe) },
            { APWorldItem.ZhornsDemonShield, new ItemGiver(OutwardItem.ZhornsDemonShield) },
            { APWorldItem.ZhornsGlowstoneDagger, new ItemGiver(OutwardItem.ZhornsGlowstoneDagger) },
            { APWorldItem.ZhornsHuntingBackpack, new ItemGiver(OutwardItem.ZhornsHuntingBackpack) },

            { APWorldItem.CurseHex, new SkillGiver(OutwardSkill.CurseHex) },
            { APWorldItem.PossessedSkill, new SkillGiver(OutwardSkill.Possessed) },

            { APWorldItem.QuestLicense, new ProgressiveSkillGiver(OutwardSkill.QuestLicense) },

            { APWorldItem.SilverCurrency, new MoneyGiver(50) },
        };

        public void GiveItemToPlayer(long archipelagoItemID, Character character)
        {
            Givers[archipelagoItemID].GiveToPlayer(character);
        }
    }
}
